### ISSUE TITLE
strange behavior of pagination in smartphone-size

### ISSUE THREAD

**Issue by torsten3d** [thewirelessguy/cornerstone#28]
Hello,
i have a good looking implementation of emm_paginate in desktop- and tablet-view, which breaks down from "1, 2, 3, …" to "»". Even if i delete all my css and just have the cornerstone-css for itself, so i think it could be a general problem.
HTML of pagination-ul is still there, but i can't find the problem why it is not visible.

Issue can bee seen here:
http://www.vorschau.salon-marita-wr.de/aktuelles/

thanks for help,kind regards
Torsten

**Comment by thewirelessguy** [comment]
It's the default behaviour of the Zurb Foundation framework. Thanks for spotting it. I hadn't realised it myself.
The solution is to add this CSS:
.pagination li {
   display: inline-block; 
}

Or if you're using Sass:
$pagination-mobile-items: false;

I've updated my example child theme to include this fix:
https://github.com/thewirelessguy/cornerstone-child-theme

**Comment by torsten3d** [comment]
Thanks for your fast response. That was the clue and saved me a lot of time.
Like your work. Using it now for the second site, since i found it last month. 

Kind regards
Torsten
