### ISSUE TITLE
Single page nav anchor links do not get active class

### ISSUE THREAD

**Issue by pjonathan** [thewirelessguy/cornerstone#29]
Have had success with other themes implementing the following in functions.php, but it does not seem to work in Cornerstone:

```
add_filter('nav_menu_css_class' , 'special_nav_class' , 10 , 2);

function special_nav_class ($classes, $item) {
    if (in_array('current-menu-item', $classes) ){
        $classes[] = 'active ';
    }
    return $classes;
}
```

**Comment by thewirelessguy** [comment]
There's already a filter on nav_menu_css_class in inc/foundation.php. To replace the function in your child theme rename your function cornerstone_active_nav_class and this will override the existing function in Cornerstone.
