### ISSUE TITLE
Localisation support?

### ISSUE THREAD

**Issue by DesignMitZweiS** [thewirelessguy/cornerstone#6]
This isn't really a technical issue rather than a feature request and I hope I'm not asking too much here. :)

Since I'm german I'd like to use my native language in the template files. Actually the only way to translate your messages (eg. in the search results) for me is to copy your files in my child theme and edit them there. This could be a pain in the ass to keep my files updated to yours. :)

Therefore I'd like to see a localization folder with some .po and .mo files.

Thanks,
Sven

**Comment by torsten3d** [comment]
Hi,
is there a actual solution for translating the files?
